[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .

; markers =
;     integration: тесты, которые поднимают реальный контейнер Mongo

addopts = # покрытие тестов, проверяем на 90% в каждом модуле проекта (.)
    --cov=.
    --cov-fail-under=90
    -ra --strict-markers
    